name: check-progress

on:
  push:
    branches:
      - '*'

jobs:
  run-jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - run: "npx jest --coverage"
